# name: Release to Main Workflow

# on:
#   push:
#     branches: [ "release" ]

# jobs:

#   build:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: read
#       pages: write
#       id-token: write

#     steps:

#    - uses: actions/checkout@v4
#
#    - name: Set up JDK 22
#      uses: actions/setup-java@v4
#      with:
#        java-version: '22'
#        distribution: 'temurin'
#        cache: maven
#
#    - name: Run tests with Maven
#      run: mvn clean test -DsuiteXmlFile=src/test/java/testng.xml
#
#    - name: Upload Reports
#      uses: actions/upload-artifact@v4
#      with:
#        name: index-${{ github.run_number }}.html
#        path: ./reports/SparkReport
#        if-no-files-found: ignore
#        retention-days: 2
#        compression-level: 6
#        overwrite: true
#
#    - name: Configure GitHub Pages
#      uses: actions/configure-pages@v5.0.0
#      with:
#        token: ${{ github.token }}
#
#    - name: Upload GitHub Pages artifact
#      uses: actions/upload-pages-artifact@v3.0.1
#      with:
#        name: github-pages
#        path: ./reports/SparkReport
#        retention-days: 7
#
#    - name: Deploy GitHub Pages site
#      uses: actions/deploy-pages@v4.0.5
#      with:
#        token: ${{ github.token }}

    # - name: Merge branch
    #   uses: devmasx/merge-branch@1.4.0
    #   with:
    #     label_name: Merging
    #     target_branch: main
    #     from_branch: release
    #     head_to_merge: GITHUB_SHA
    #     github_token: ${{ github.token }}
              
          
